###


GET http://localhost:4000/



###


GET http://localhost:4000/offer
Authorization: barer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMjdlOWEzNDA0YzExZWE4YTEyOTNkNyIsImlhdCI6MTY0NjgyNjg0NCwiZXhwIjoxNjQ2ODMwNDQ0fQ.C2KNTcqIDPkM47kXCL0IUCFUt4H0_y_dseKbO3dw_IE
###


GET http://localhost:4000/offer/620d3347abfb42d96325fcc5

###


POST http://localhost:4000/offer
Authorization: barer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMjdlOWEzNDA0YzExZWE4YTEyOTNkNyIsImlhdCI6MTY0NjgyNjg0NCwiZXhwIjoxNjQ2ODMwNDQ0fQ.C2KNTcqIDPkM47kXCL0IUCFUt4H0_y_dseKbO3dw_IE
Content-Type: application/json

{
        "Description":"hi",   
        "HeadLine":"hello",
        "Price" :10,
        "Coupon":"free dinner",
        "IdOffer" :1,
        "Status":"now",
        "Profession": ["sport"],  
        "User":"62277413fe8636f7c2c9aff2",      
        "IntrestedVerify":false
}

###


POST http://localhost:4000/auth/register
Content-Type: application/json

{
    "Username": "yossi8",       
    "Password":"5566", 
    "Sex":"undefind",
    "Age":28, 
    "Followers":10,
    "Profession":["Art","Sport"],
    "Platform":["instagram","youtube"], 
    "NumberOfPosts":20,
    "Company":false,
    "Influencer":true 
}

###


POST http://localhost:4000/auth/login
Content-Type: application/json

{
    "Username" : "yossi8",
    "Password" : "5566"
}

###


POST http://localhost:4000/auth/logout
Content-Type: application/json

{
    "message" : "you have been logedout",
    "sender" : "Yossi"
}
###


GET  http://localhost:4000/auth/refreshToken
Authorization: barer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMjhjZmI3MmI2ZjNmYjUyZTRlNDEwZCIsImlhdCI6MTY0Njg0MTc4Nn0.mFXobp3GLlH8DNxH2tSRukNOv5S8u5BPTrtKoV9tVpE