###


GET http://localhost:4000/

###


GET http://localhost:4000/offer/getoffers
Authorization: barer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMmYzMzliNjIzMGRkYTgwY2RkYjdkNSIsImlhdCI6MTY0NzI2MDU3MywiZXhwIjoxNjQ3MjY0MTczfQ.Qc8pmjK44hJkepiAiIITwV5iw3OLWZqF9Z2jBMkcf2E
###


GET http://localhost:4000/offer/getOfferById/622e2fed8fba1393eee2da12
Authorization: barer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMmRjZWNmY2RiMTcwNGU1MDJmODg0NiIsImlhdCI6MTY0NzE5NDQ1NCwiZXhwIjoxNjQ3MTk4MDU0fQ.4WBlTtFyAoiWAOFitnxHLfSDGFb14sVbF7BW5U5wkS0

###
POST  http://localhost:4000/offer/editOffer/622b69c403b68fe10748fd49
Authorization: barer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMmI2ODZhYmQ4ZWQ5MmFiN2M4YjE5ZSIsImlhdCI6MTY0NzAxMzE5MiwiZXhwIjoxNjQ3MDE2NzkyfQ.DjqLuCC7zqX4NyDG6lsf4zszym0Wh2zaBYTetzGhu74
Content-Type: application/json

{
        "Description":"1111",   
        "HeadLine":"hello",
        "Price" :10,
        "Coupon":"free dinner",
        "IdOffer" :1,
        "Status":"now",
        "Profession": ["sport"],  
        "User":"62277413fe8636f7c2c9aff2",      
        "IntrestedVerify":false
}
###



POST http://localhost:4000/offer/addNewOffer
Authorization: barer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyM2JhNTMxNjFhNTAwM2Y1MGU3ODllMSIsImlhdCI6MTY0ODUwNTQzNywiZXhwIjoxNjQ4NTEyNjM3fQ.Cj16QVBxEYFJKsLm0IUNPxfTtx9JYwPacw6d4MCSJ-I
Content-Type: application/json

{
        "Description":"koko",   
        "HeadLine":"yoyo",
        "FinishDate":"14.6.22",
        "Price" :10,
        "Coupon":"1$",
        "IdOffer" :100,
        "Status":"now",
        "Profession": ["sport"],  
        "User":"loljjji",      
        "IntrestedVerify":false
}

###


POST http://localhost:4000/auth/register
Content-Type: application/json

{
    "Username": "bar",       
    "Password":"5566", 
    "Email": "email@email.email",
    "Sex":"undefind",
    "Age":28, 
    "Followers":10,
    "Profession":["Art","Sport"],
    "Platform":["instagram","youtube"], 
    "NumberOfPosts":20,
    "Company":false,
    "Influencer":true 
}

###


POST http://localhost:4000/auth/login
Content-Type: application/json

{
    "Username" : "bar",
    "Password" : "5566"
}

###


POST http://localhost:4000/auth/logout
Authorization: barer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMjhkZDRmNjg5ZDU0ZjgyNWIxOWUyNiIsImlhdCI6MTY0Njg0NTI5MH0.XOijRz4KasAgAaPx7HS1pCvIpR7tFo16hezjN3OjXB8
###
GET  http://localhost:4000/auth/refreshToken
Authorization: barer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMjhkYmFmM2QxYjdjM2E2NTA4YjRiOCIsImlhdCI6MTY0Njg0NDg1Mn0.gJCd-Uqf5UstpylX6Ni3xkcNGzC-5rJnPKD_6bvuw28
###
GET http://localhost:4000/offer/deleteOffer/622b5bc167452bd62e2e8454
Authorization: barer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMmI1NGQ2ZjkzNDE5NWU5NjEwMzU4YyIsImlhdCI6MTY0NzAwODg4NiwiZXhwIjoxNjQ3MDEyNDg2fQ.d_Oi-oNs56TsQjwZV7K6niCW-suRXqgKJE4sj4accxA

###

###
GET  http://localhost:4000/auth/refreshToken
Authorization: barer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyM2JhNTMxNjFhNTAwM2Y1MGU3ODllMSIsImlhdCI6MTY0ODQyMTA3MiwiZXhwIjoxNjQ4NDIxMTUyfQ.SqpgQon4h8jJlBIjDrUvzwyFLCvpbzn_-BZfqpmbc_o

###
GET http://localhost:4000/users/getUser/bari
Authorization: barer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMmRjZWNmY2RiMTcwNGU1MDJmODg0NiIsImlhdCI6MTY0NzI0NjYyNywiZXhwIjoxNjQ3MjUwMjI3fQ.fePzDs3Sq-s-RhQ-Feu3XaU_uKpwxALNhrgIEj5oqwo


###
GET http://localhost:4000/users/getUserById/622dcecfcdb1704e502f8846
Authorization: barer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMmRjZWNmY2RiMTcwNGU1MDJmODg0NiIsImlhdCI6MTY0NzI0NjYyNywiZXhwIjoxNjQ3MjUwMjI3fQ.fePzDs3Sq-s-RhQ-Feu3XaU_uKpwxALNhrgIEj5oqwo


###
POST  http://localhost:4000/users/editUser/amit
Authorization: barer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMmY2MDk1Mzk1ODVjMWMxZWFlZjI0YSIsImlhdCI6MTY0NzI3MzM2OCwiZXhwIjoxNjQ3Mjc2OTY4fQ.zmVtQGFHmz1MWZZ34wlo08Qt1Q_LlD1ho8bAQVpLcQE
Content-Type: application/json

{
    "Username": "amit",       
    "Password":"5566", 
    "Email": "email@email.email1",
    "Sex":"undefind",
    "Age":"28845", 
    "Followers":"11",
    "Profession":["Art","Sport"],
    "Platform":["instagram","youtube"], 
    "NumberOfPosts":"20",
    "Company":false,
    "Influencer":true 
}
###
GET http://localhost:4000/candidates/getCandidates/100
Authorization: barer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMzVlYTk1ZGQ0YjcyYWFkYzc1NTJlZiIsImlhdCI6MTY0NzcwMDYzMSwiZXhwIjoxNjQ3NzA0MjMxfQ.TnuSorNbSNYBNXLkAmJJKe4LBhZx5y2cPazJAc3Z5kg

###
GET http://localhost:4000/auth/getUserByUserNameInSignIn/amit
Content-Type: application/
###

GET http://localhost:4000/search/getOfferFromFreeSearch/koko
Authorization: barer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyM2JhNTMxNjFhNTAwM2Y1MGU3ODllMSIsImlhdCI6MTY0ODUwNTQzNywiZXhwIjoxNjQ4NTEyNjM3fQ.Cj16QVBxEYFJKsLm0IUNPxfTtx9JYwPacw6d4MCSJ-I

###
GET http://localhost:4000/search/getOfferFromSpecificSearch/koko/momo/null/null/null/null/sport/yossi
Authorization: barer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyM2JhNTMxNjFhNTAwM2Y1MGU3ODllMSIsImlhdCI6MTY0ODY2Mjc3MSwiZXhwIjoxNjQ4NjY5OTcxfQ.0uBjcbr0VAiYX3dOkLvDXJHx8MPOLrgP01SyxNquqNg
