###


GET http://localhost:4000/



###


GET http://localhost:4000/offer
Authorization: barer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMjc4MmVhZThkYjAxMjU3MTY5NmNhOCIsImlhdCI6MTY0Njc1Njg4NiwiZXhwIjoxNjQ2NzYwNDg2fQ.mNSdMm5BvXxJwSPJNWxvqEpVVLirY9ib6FCJT06pJa8
###


GET http://localhost:4000/offer/620d3347abfb42d96325fcc5

###


POST http://localhost:4000/offer
Authorization: barer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMjc4MmVhZThkYjAxMjU3MTY5NmNhOCIsImlhdCI6MTY0Njc1Njg4NiwiZXhwIjoxNjQ2NzYwNDg2fQ.mNSdMm5BvXxJwSPJNWxvqEpVVLirY9ib6FCJT06pJa8
Content-Type: application/json

{
        "Description":"hi",   
        "HeadLine":"hello" ,
        "Price" :10,
        "Coupon":"free dinner",
        "IdOffer" :1,
        "Status":"now",
        "Proffesion": ["sport"],  
        "User":{"Username":"hello","Password":"12345678"},      
        "IntrestedVerify":false
}

###


POST http://localhost:4000/auth/register
Content-Type: application/json

{
    "Username": "yossi6",       
    "Password":"5566", 
    "Sex":"undefind",
    "Age":28, 
    "Followers":10,
    "Profession":["Art","Sport"],
    "Platform":["instagram","youtube"], 
    "NumberOfPosts":20,
    "Company":false,
    "Influencer":true 
}

###


POST http://localhost:4000/auth/login
Content-Type: application/json

{
    "Username" : "yossi6",
    "Password" : "5566"
}

###


POST http://localhost:4000/auth/logout
Content-Type: application/json

{
    "message" : "this is my new offer",
    "sender" : "Yossi"
}